EcommerceWebApplication_Backup_2018.05.29_07.05.50/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EcommerceWebApplication.Models.EF;

namespace EcommerceWebApplication.Controllers
{
    public class CustomersController : Controller
    {
        private ECommerce db = new ECommerce();
        private Customer customer = new Customer();
        private CustomerLastLogin lastlogin = new CustomerLastLogin();

        //public Customer Customer1 { get => Customer; set => Customer = value; }

        // GET: Customers
        public ActionResult Index()
        {
           return View(db.Customers.ToList());
        }

        // GET: Customers/Details/5
       

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }
        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CustomerName,State,Address,ContactNumber,email,CustomerPassword")] Customer customer)
        {
            if (ModelState.IsValid)
            {

                //customer.CustomerID++; ;
               // db.ExecuteCommand("SET IDENTITY_INSERT MyTable ON");
                db.Customers.Add(customer);
                db.SaveChanges();
                //id = customer.CustomerID;
                //id++;
                return RedirectToAction("Index");
            }
            return View(customer);
        }

    public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login([Bind(Include = "Email,CustomerPassword")]UserLogin user)
        {
            if (ModelState.IsValid)
                {
                    var obj = db.Customers.Where(a => a.email.Equals(user.email) && a.CustomerPassword.Equals(user.CustomerPassword)).FirstOrDefault();
                   

                if (obj!=null)
                {
                    //Creating session after user login
                    Session["CustomerID"] = obj.CustomerID.ToString();
                    Session["email"] = obj.email.ToString();
                    Session["name"] = obj.CustomerName.ToString();
                    Session["Role"] = obj.Role;

                    //Session["LastLogin"] = lastlogin.LoginDateTime;
                    //Save last login time in session using proc
                    int customerID = Convert.ToInt32(Session["CustomerID"]);
                    var result = Customer(customerID).FirstOrDefault();
                    Session["LastLogin"] = result.LoginDateTime.ToString();

                    //Store Last login Details of customer
                    DateTime localDate = DateTime.Now;
                    lastlogin.CustomerID = obj.CustomerID;

                    lastlogin.LoginDateTime = localDate;
                    db.CustomerLastLogins.Add(lastlogin);
                    db.SaveChanges();
                    return RedirectToAction("Cart", "ShoppingCart");
                }
                }
            return View("Login");
        }

        private List<usps_LastUserLogin_Result> Customer(int CustomerID)
        {
            using (ECommerce db = new ECommerce())
            {
                return db.usps_LastUserLogin(CustomerID).ToList();
            }
        }

        public ActionResult Welcome()
        {
            if(Session["CustomerID"]!=null)
            {
               //return RedirectToAction("Cart","ShoppingCart");
                return View();
            }

            else
            {
                return RedirectToAction("Login");
            }
            
        }
     
        // POST: Customers/Delete/5
    

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

EcommerceWebApplication_Backup_2018.05.29_07.05.50/Controllers/OrderHistoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EcommerceWebApplication.Models.EF;
using EcommerceWebApplication.Models;

namespace EcommerceWebApplication.Controllers
{
    public class OrderHistoryController : Controller
    {
        // GET: OrderHistory
        public ActionResult Index()
        {
            ProdutViewModel product = new ProdutViewModel();
            using (ECommerce context = new ECommerce())
            {
                product.ShoppingCart = context.ShoppingCarts.ToList();
            }
                return View(product);
        }
    }
}

EcommerceWebApplication_Backup_2018.05.29_07.05.50/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Style/StyleSheet1.css" rel="stylesheet" />
    

	<!--This bundle was moved by the Telerik VS Extensions for compatibility reasons-->
	@Scripts.Render("~/bundles/jquery")
	<link href="@Url.Content("~/Content/kendo/2018.2.516/kendo.common-bootstrap.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2018.2.516/kendo.mobile.all.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2018.2.516/kendo.bootstrap.min.css")" rel="stylesheet" type="text/css" />
	<script src="@Url.Content("~/Scripts/kendo/2018.2.516/jquery.min.js")"></script>
	<script src="@Url.Content("~/Scripts/kendo/2018.2.516/jszip.min.js")"></script>
	<script src="@Url.Content("~/Scripts/kendo/2018.2.516/kendo.all.min.js")"></script>
	<script src="@Url.Content("~/Scripts/kendo/2018.2.516/kendo.aspnetmvc.min.js")"></script>
	<script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>
</head>
<body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Response Shopping", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse"> 
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                        <li>@Html.ActionLink("Products", "Details", "ProductInfoes")</li>
                        @*<li>@Html.ActionLink("Contact", "Index", "Home")</li>*@
                        <li>@Html.ActionLink("Signup", "Create", "Customers")</li>
                        <li>@Html.ActionLink("Login", "Login", "Customers")</li>
                        <li>@Html.ActionLink("Cart", "Cart", "ShoppingCart")</li>
                        <li>@Html.ActionLink("History", "Index", "OrderHistory")</li>
                        @Html.Action("Index", "Roles")
                    </ul>
                    <div class="navbar-right">
                        <p class="navbar-text">Welcome @Session["name"]</p>
                        @if (@Session["name"] != null)
                        {
                            <p class="navbar-text">Last Logged: @Session["LastLogin"]</p>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="container body-content" style="
    width:100%; height:100%">
            @RenderBody()

        </div>

        <footer class="footer">
            <div class="container">
                <div class="row footer-widgets">

                </div>
                </div>
            </footer>

                    
                    @Scripts.Render("~/bundles/bootstrap")
                    @RenderSection("scripts", required: false)

</body>
</html>

   